version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.4
      - test-3.5

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: sudo pip install flake8 pytest pytz
  - run:
      name: Lint
      command: flake8
  - run:
      name: Test
      command: python setup.py test

jobs:
  test-2.7:
    <<: *defaults
    docker:
    - image: circleci/python:2.7
  test-3.4:
    <<: *defaults
    docker:
    - image: circleci/python:3.4
  test-3.5:
    <<: *defaults
    docker:
    - image: circleci/python:3.5
